psql bloom < file_sql_bloom/thread_0.sql > time_result_btree/thread_0.txt | bash measure_ram.sh 0
psql bloom < file_sql_bloom/thread_2.sql > time_result_btree/thread_2.txt | bash measure_ram.sh 2
psql bloom < file_sql_bloom/thread_4.sql > time_result_btree/thread_4.txt | bash measure_ram.sh 4
psql bloom < file_sql_bloom/thread_6.sql > time_result_btree/thread_6.txt | bash measure_ram.sh 6
psql bloom < file_sql_bloom/thread_8.sql > time_result_btree/thread_8.txt | bash measure_ram.sh 8
psql bloom < file_sql_bloom/thread_10.sql > time_result_btree/thread_10.txt | bash measure_ram.sh 10
psql bloom < file_sql_bloom/thread_12.sql > time_result_btree/thread_12.txt | bash measure_ram.sh 12
psql bloom < file_sql_bloom/thread_14.sql > time_result_btree/thread_14.txt | bash measure_ram.sh 14
psql bloom < file_sql_bloom/thread_16.sql > time_result_btree/thread_16.txt | bash measure_ram.sh 16
psql bloom < file_sql_bloom/thread_18.sql > time_result_btree/thread_18.txt | bash measure_ram.sh 18
psql bloom < file_sql_bloom/thread_20.sql > time_result_btree/thread_20.txt | bash measure_ram.sh 20
psql bloom < file_sql_bloom/thread_22.sql > time_result_btree/thread_22.txt | bash measure_ram.sh 22
psql bloom < file_sql_bloom/thread_24.sql > time_result_btree/thread_24.txt | bash measure_ram.sh 24
psql bloom < file_sql_bloom/thread_26.sql > time_result_btree/thread_26.txt | bash measure_ram.sh 26
psql bloom < file_sql_bloom/thread_28.sql > time_result_btree/thread_28.txt | bash measure_ram.sh 28
psql bloom < file_sql_bloom/thread_30.sql > time_result_btree/thread_30.txt | bash measure_ram.sh 30
psql bloom < file_sql_bloom/thread_32.sql > time_result_btree/thread_32.txt | bash measure_ram.sh 32
psql bloom < file_sql_bloom/thread_34.sql > time_result_btree/thread_34.txt | bash measure_ram.sh 34
psql bloom < file_sql_bloom/thread_36.sql > time_result_btree/thread_36.txt | bash measure_ram.sh 36
psql bloom < file_sql_bloom/thread_38.sql > time_result_btree/thread_38.txt | bash measure_ram.sh 38
psql bloom < file_sql_bloom/thread_40.sql > time_result_btree/thread_40.txt | bash measure_ram.sh 40
psql bloom < file_sql_bloom/thread_42.sql > time_result_btree/thread_42.txt | bash measure_ram.sh 42
psql bloom < file_sql_bloom/thread_44.sql > time_result_btree/thread_44.txt | bash measure_ram.sh 44
psql bloom < file_sql_bloom/thread_46.sql > time_result_btree/thread_46.txt | bash measure_ram.sh 46
psql bloom < file_sql_bloom/thread_48.sql > time_result_btree/thread_48.txt | bash measure_ram.sh 48
psql bloom < file_sql_bloom/thread_50.sql > time_result_btree/thread_50.txt | bash measure_ram.sh 50
psql bloom < file_sql_bloom/thread_52.sql > time_result_btree/thread_52.txt | bash measure_ram.sh 52
psql bloom < file_sql_bloom/thread_54.sql > time_result_btree/thread_54.txt | bash measure_ram.sh 54
psql bloom < file_sql_bloom/thread_56.sql > time_result_btree/thread_56.txt | bash measure_ram.sh 56
psql bloom < file_sql_bloom/thread_58.sql > time_result_btree/thread_58.txt | bash measure_ram.sh 58
