psql bloom < file_sql_bloom/length_4.sql > time_result_bloom/length_4.txt | bash measure_ram.sh 4
psql bloom < file_sql_bloom/length_5.sql > time_result_bloom/length_5.txt | bash measure_ram.sh 5
psql bloom < file_sql_bloom/length_6.sql > time_result_bloom/length_6.txt | bash measure_ram.sh 6
psql bloom < file_sql_bloom/length_8.sql > time_result_bloom/length_8.txt | bash measure_ram.sh 8
psql bloom < file_sql_bloom/length_9.sql > time_result_bloom/length_9.txt | bash measure_ram.sh 9
psql bloom < file_sql_bloom/length_11.sql > time_result_bloom/length_11.txt | bash measure_ram.sh 11
psql bloom < file_sql_bloom/length_14.sql > time_result_bloom/length_14.txt | bash measure_ram.sh 14
psql bloom < file_sql_bloom/length_17.sql > time_result_bloom/length_17.txt | bash measure_ram.sh 17
psql bloom < file_sql_bloom/length_20.sql > time_result_bloom/length_20.txt | bash measure_ram.sh 20
psql bloom < file_sql_bloom/length_24.sql > time_result_bloom/length_24.txt | bash measure_ram.sh 24
psql bloom < file_sql_bloom/length_29.sql > time_result_bloom/length_29.txt | bash measure_ram.sh 29
psql bloom < file_sql_bloom/length_35.sql > time_result_bloom/length_35.txt | bash measure_ram.sh 35
psql bloom < file_sql_bloom/length_42.sql > time_result_bloom/length_42.txt | bash measure_ram.sh 42
psql bloom < file_sql_bloom/length_51.sql > time_result_bloom/length_51.txt | bash measure_ram.sh 51
psql bloom < file_sql_bloom/length_61.sql > time_result_bloom/length_61.txt | bash measure_ram.sh 61
psql bloom < file_sql_bloom/length_73.sql > time_result_bloom/length_73.txt | bash measure_ram.sh 73
psql bloom < file_sql_bloom/length_88.sql > time_result_bloom/length_88.txt | bash measure_ram.sh 88
psql bloom < file_sql_bloom/length_106.sql > time_result_bloom/length_106.txt | bash measure_ram.sh 106
psql bloom < file_sql_bloom/length_127.sql > time_result_bloom/length_127.txt | bash measure_ram.sh 127
psql bloom < file_sql_bloom/length_153.sql > time_result_bloom/length_153.txt | bash measure_ram.sh 153
psql bloom < file_sql_bloom/length_184.sql > time_result_bloom/length_184.txt | bash measure_ram.sh 184
psql bloom < file_sql_bloom/length_220.sql > time_result_bloom/length_220.txt | bash measure_ram.sh 220
psql bloom < file_sql_bloom/length_264.sql > time_result_bloom/length_264.txt | bash measure_ram.sh 264
psql bloom < file_sql_bloom/length_317.sql > time_result_bloom/length_317.txt | bash measure_ram.sh 317
psql bloom < file_sql_bloom/length_381.sql > time_result_bloom/length_381.txt | bash measure_ram.sh 381
psql bloom < file_sql_bloom/length_457.sql > time_result_bloom/length_457.txt | bash measure_ram.sh 457
psql bloom < file_sql_bloom/length_549.sql > time_result_bloom/length_549.txt | bash measure_ram.sh 549
psql bloom < file_sql_bloom/length_659.sql > time_result_bloom/length_659.txt | bash measure_ram.sh 659
psql bloom < file_sql_bloom/length_791.sql > time_result_bloom/length_791.txt | bash measure_ram.sh 791
psql bloom < file_sql_bloom/length_949.sql > time_result_bloom/length_949.txt | bash measure_ram.sh 949
psql bloom < file_sql_bloom/length_1139.sql > time_result_bloom/length_1139.txt | bash measure_ram.sh 1139
psql bloom < file_sql_bloom/length_1367.sql > time_result_bloom/length_1367.txt | bash measure_ram.sh 1367
psql bloom < file_sql_bloom/length_1640.sql > time_result_bloom/length_1640.txt | bash measure_ram.sh 1640
psql bloom < file_sql_bloom/length_1968.sql > time_result_bloom/length_1968.txt | bash measure_ram.sh 1968
psql bloom < file_sql_bloom/length_2362.sql > time_result_bloom/length_2362.txt | bash measure_ram.sh 2362
psql bloom < file_sql_bloom/length_2835.sql > time_result_bloom/length_2835.txt | bash measure_ram.sh 2835
psql bloom < file_sql_bloom/length_3402.sql > time_result_bloom/length_3402.txt | bash measure_ram.sh 3402
psql bloom < file_sql_bloom/length_4082.sql > time_result_bloom/length_4082.txt | bash measure_ram.sh 4082
