psql bloom < file_sql_bloom/column_1.sql > time_result_btree/column_1.txt | bash measure_ram.sh 1
psql bloom < file_sql_bloom/column_2.sql > time_result_btree/column_2.txt | bash measure_ram.sh 2
psql bloom < file_sql_bloom/column_3.sql > time_result_btree/column_3.txt | bash measure_ram.sh 3
psql bloom < file_sql_bloom/column_4.sql > time_result_btree/column_4.txt | bash measure_ram.sh 4
psql bloom < file_sql_bloom/column_5.sql > time_result_btree/column_5.txt | bash measure_ram.sh 5
psql bloom < file_sql_bloom/column_6.sql > time_result_btree/column_6.txt | bash measure_ram.sh 6
psql bloom < file_sql_bloom/column_7.sql > time_result_btree/column_7.txt | bash measure_ram.sh 7
psql bloom < file_sql_bloom/column_8.sql > time_result_btree/column_8.txt | bash measure_ram.sh 8
psql bloom < file_sql_bloom/column_9.sql > time_result_btree/column_9.txt | bash measure_ram.sh 9
psql bloom < file_sql_bloom/column_10.sql > time_result_btree/column_10.txt | bash measure_ram.sh 10
psql bloom < file_sql_bloom/column_11.sql > time_result_btree/column_11.txt | bash measure_ram.sh 11
psql bloom < file_sql_bloom/column_12.sql > time_result_btree/column_12.txt | bash measure_ram.sh 12
psql bloom < file_sql_bloom/column_13.sql > time_result_btree/column_13.txt | bash measure_ram.sh 13
psql bloom < file_sql_bloom/column_14.sql > time_result_btree/column_14.txt | bash measure_ram.sh 14
psql bloom < file_sql_bloom/column_15.sql > time_result_btree/column_15.txt | bash measure_ram.sh 15
psql bloom < file_sql_bloom/column_16.sql > time_result_btree/column_16.txt | bash measure_ram.sh 16
psql bloom < file_sql_bloom/column_17.sql > time_result_btree/column_17.txt | bash measure_ram.sh 17
psql bloom < file_sql_bloom/column_18.sql > time_result_btree/column_18.txt | bash measure_ram.sh 18
psql bloom < file_sql_bloom/column_19.sql > time_result_btree/column_19.txt | bash measure_ram.sh 19
psql bloom < file_sql_bloom/column_20.sql > time_result_btree/column_20.txt | bash measure_ram.sh 20
psql bloom < file_sql_bloom/column_21.sql > time_result_btree/column_21.txt | bash measure_ram.sh 21
psql bloom < file_sql_bloom/column_22.sql > time_result_btree/column_22.txt | bash measure_ram.sh 22
psql bloom < file_sql_bloom/column_23.sql > time_result_btree/column_23.txt | bash measure_ram.sh 23
psql bloom < file_sql_bloom/column_24.sql > time_result_btree/column_24.txt | bash measure_ram.sh 24
psql bloom < file_sql_bloom/column_25.sql > time_result_btree/column_25.txt | bash measure_ram.sh 25
psql bloom < file_sql_bloom/column_26.sql > time_result_btree/column_26.txt | bash measure_ram.sh 26
psql bloom < file_sql_bloom/column_27.sql > time_result_btree/column_27.txt | bash measure_ram.sh 27
psql bloom < file_sql_bloom/column_28.sql > time_result_btree/column_28.txt | bash measure_ram.sh 28
psql bloom < file_sql_bloom/column_29.sql > time_result_btree/column_29.txt | bash measure_ram.sh 29
psql bloom < file_sql_bloom/column_30.sql > time_result_btree/column_30.txt | bash measure_ram.sh 30
psql bloom < file_sql_bloom/column_31.sql > time_result_btree/column_31.txt | bash measure_ram.sh 31
